version: '3'
services:
  mqtt_to_kafka:
    build: .
    image: mic/mqtt_to_kafka:1.0.0
    container_name: mqtt_to_kafka
    environment:
      - TZ=Asia/Bangkok
    privileged: true
    volumes:
      - ./.env:/app/.env
    restart: always